repos:
  - repo: local
    hooks:
      - id: rust-check
        name: rustfmt and clippy
        entry: ./scripts/check-rust.sh check
        language: script
        pass_filenames: false
        files: \.rs$

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        args: ['-config-file', '.github/actionlint.yaml']

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: ^(scripts|tools)/
        types_or: [sh, bash, shell]
        args: ['-x']
