[package]
name = "qcow2"
version = "0.1.0"
edition = "2021"
description = "QCOW2 format parsing for bare-metal guest operations"
license = "Apache-2.0"

[features]
decompress = ["miniz_oxide"]
decompress-zstd = ["ruzstd"]
compress = ["miniz_oxide", "miniz_oxide/with-alloc"]

[dependencies]
shared = { path = "../../shared" }
miniz_oxide = { version = "0.8", default-features = false, optional = true }
ruzstd = { version = "0.8", default-features = false, optional = true }

[lib]
# No std, this is used by bare-metal code
