[package]
name = "compare"
version = "0.1.0"
edition = "2021"
description = "Compare operation: image data comparison"
license = "Apache-2.0"

[dependencies]
shared = { path = "../../shared" }
qcow2 = { path = "../../crates/qcow2", features = ["decompress"] }

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
