[package]
name = "compare"
version = "0.1.0"
edition = "2021"
description = "Compare operation: image data comparison"
license = "Apache-2.0"

[dependencies]
shared = { path = "../../shared" }
qcow2 = { path = "../../crates/qcow2", features = [
    "decompress", "decompress-zstd", "aes-decrypt",
    "luks-decrypt", "vmdk-decompress",
    "vhd-input", "vhdx-input",
] }
luks = { path = "../../crates/luks", features = ["decrypt"] }

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
