[package]
name = "check"
version = "0.1.0"
edition = "2021"
description = "Check operation: validate image structural integrity"
license = "Apache-2.0"

[dependencies]
shared = { path = "../../shared" }
qcow2 = { path = "../../crates/qcow2" }
vmdk = { path = "../../crates/vmdk" }

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
